### ISSUE TITLE
Mapa Mental

### ISSUE THREAD

**Issue by lucero012** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-lucero012#1]
[WEB 3.0.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-lucero012/files/14671548/WEB.3.0.pdf)

**Comment by Julissamigdalia** [comment]
buen trabajo:
calificacion:
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
